test_toast/urls.py
from django.contrib import admin
from django.urls import include, path
from toast_cal import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("toast_cal/", include("toast_cal.urls")),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("findInfo/", views.findInfo, name="findInfo"),
    path("findId/", views.findId, name="findId"),
    path("findPass/", views.findPass, name="findPass"),
    path("changePw/",views.changePw, name="changePw"),
]

toast_cal/urls.py
from django.urls import path

from toast_cal import views, crud

app_name = "toast_cal"

urlpatterns = [
    path("", views.calendar, name="calendar"),  # 로그인시 메인 화면
    # 캘린더 기능들
    path("ourstores/", crud.ourstores, name="ourstores"),
    path("calSetData/", crud.calSetData, name="calSetData"),
    path("create/", crud.createData, name="createData"),
    path("update/", crud.updateData, name="updateData"),
    path("delete/", crud.deleteData, name="deleteData"),
    # 우측 네비게이션
    path("dateList/", crud.dateList, name="dateList"),
    path("getWeekSchedule/", crud.getWeekSchedule, name="getWeekSchedule"),
    # 학생 기능들
    path("checked/", crud.checked, name="checked"),
    path("department/", crud.department, name="department"),  # 강의 버튼클릭시 학과 가져옴
    path("subject/", crud.subject, name="subject"),  # 학과 선택시 해당 과목 가져옴
    path("chanege_type/", crud.chanege_type, name="chanege_type"),  # 과목선택시 해당 이수구분 가져옴
    path("lecture_lookup/", crud.lecture_lookup, name="lecture_lookup"),  # 조회
    path("lecture_save/", crud.lecture_save, name="lecture_save"),  # 강의 저장
    path(
        "student_lecture_load/", crud.student_lecture_load, name="student_lecture_load"
    ),  # 학생 강의 불러오기
    path(
        "student_lecture_delete/",
        crud.student_lecture_delete,
        name="student_lecture_delete",
    ),  # 학생 강의 삭제
    path(
        "stdVoteJoinTable/", crud.stdVoteJoinTable, name="stdVoteJoinTable"
    ),  # 학생 투표 참여 데이터 불러오기
    path("joinCheck/", crud.joinCheck, name="joinCheck"),
    path(
        "stdVoteSelectData/", crud.stdVoteSelectData, name="stdVoteSelectData"
    ),  # 학생 투표 참여 페이지 상세내용 불러오기
    path(
        "takeVoteSave/", crud.takeVoteSave, name="takeVoteSave"
    ),  # 학생 투표 시간 선택 시 데이터베이스에 저장
    path("student_voteTable/", crud.student_voteTable, name="student_voteTable"),
    # vote 테이블의 아무값이나 받은 테스트 데이터
    path("voteSelectTest/", crud.voteSelectTest, name="voteSelectTest/"),
    path("getAllStudent/", crud.getAllStudent, name="getAllStudent/"),
    path("getLectureInfo/", crud.getLectureInfo, name="getLectureInfo"),  # 학생 투표 강의 정보
    # 교수 기능들
    path("voteTable/", crud.voteTable, name="voteTable"),
    path("voteChart/", crud.voteChart, name="voteChart"),
    path("makeSubject/", crud.makeSubject, name="makeSubject"),
    path(
        "pro_lecture_table/", crud.pro_lecture_table, name="pro_lecture_table"
    ),  # 교수 강의 테이블 출력
    path(
        "professor_lecture_delete/",
        crud.professor_lecture_delete,
        name="professor_lecture_delete",
    ),  # 교수 강의 삭제
    path(
        "pro_vote_update_table/",
        crud.pro_vote_update_table,
        name="pro_vote_update_table",
    ),
    path("lec_Check/", crud.lec_Check, name="lec_Check"),
    path("pro_vote_info/", crud.pro_vote_info, name="pro_vote_info"),
    # 교수 투표 관련
    path("subject_info/", crud.subject_info, name="subject_info"),
    path("create_Vote/", crud.create_Vote, name="create_Vote"),
    path("delete_Vote/", crud.delete_Vote, name="delete_Vote"),
    path("update_Vote/", crud.update_Vote, name="update_Vote"),
    path("check_Vote/", crud.check_Vote, name="check_Vote"),
    path("manageInfo/", views.manageInfo, name="manageInfo"),
    path("loginInfo/", views.loginInfo, name="loginInfo"),
    path("modifyInfo/", views.modifyInfo, name="modifyInfo"),
    path("getVoteInfo/", crud.getVoteInfo, name="getVoteInfo"),
    path("voteConfirm/", crud.voteConfirm, name="voteConfirm"),
    path("createExamData/", crud.createExamData, name="createExamData"),
    path("bring_Comment/", crud.bring_Comment, name="bring_Comment"),  # 코멘트 가져오기
    path("bring_StdName/", crud.bring_StdName, name="bring_StdName"),
    # 공통 기능들
    path("deleteCalendars/", crud.deleteCalendars, name="deleteCalendars"),
    path("makeCalendars/", crud.makeCalendars, name="makeCalendars"),
    path("signout/", views.signout, name="signout"),
    path("pubCalSave/", crud.pubCalSave, name="pubCalSave"),
    path("check_user_subject/", crud.check_user_subject, name="check_user_subject"),
    # 공용 캘린더 부분들
    path("pubCalSetData/", crud.pubCalSetData, name="pubCalSetData"),
    path("pro_lecture/", crud.pro_lecture, name="pro_lecture"),
    path("pubCalSave/", crud.pubCalSave, name="pubCalSave"),
    path("pubCalLoad/", crud.pubCalLoad, name="pubCalLoad"),
    path("voteTimeLoad/", crud.voteTimeLoad, name="voteTimeLoad"),  # 투표 가능 시간대 불러오기
    path("voteTimeSave/", crud.voteTimeSave, name="voteTimeSave"),  # 투표 가능 시간대 저장
    # [2020-11-07 06:21] 새 기능
    path(
        "renewal_vote_status/", crud.renewal_vote_status, name="renewal_vote_status"
    ),  # 투표 상태 갱신
]

toast_cal/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core import serializers
from .models import *  # Ava_Time, Calendar, PubCalendar, Student, Professor, Subject, Student_lecture

from django.contrib.auth.hashers import make_password, check_password

# 메인 홈페이지 리턴
def index(request):
    return render(request, "index.html")


def calendar(request):
    return render(request, "calendar.html")


# 회원가입과 로그인 기능에서 Student, Professor 조건문으로 분기
# 회원가입 페이지
def signup(request):
    if request.method == "POST":
        userType = request.POST["userType"]
        userID = request.POST["userID"]
        password = request.POST["password"]
        password_check = request.POST["password_check"]

        if password == password_check:
            if userType == "student":
                user_data = Student(
                    userID=userID,
                    password=make_password(password),
                    username=request.POST["username"],
                    department=request.POST["department"],
                    studentID=request.POST["studentID"],
                    email=request.POST["email"],
                    phone=request.POST["phone"],
                )
                user_data.save()

                return redirect("login")
            elif userType == "professor":
                user_data = Professor(
                    userID=userID,
                    password=make_password(password),
                    username=request.POST["username"],
                    department=request.POST["department"],
                    email=request.POST["email"],
                    phone=request.POST["phone"],
                )
                user_data.save()

                return redirect("login")

        return render(request, "signup.html")
    return render(request, "signup.html")


# 로그인 페이지
def login(request):
    if request.method == "POST":
        userID = request.POST.get("userID", None)
        password = request.POST.get("password", None)

        if not (userID and password):
            return render(request, "login.html", {"error": "아이디와 비밀번호를 모두 입력해주세요."})
        else:
            user_data = "1"  # 더미데이터로 변수 생성
            userName = "1"  # 더미데이터로 변수 생성
            userType = "1"  # 더미데이터로 변수 생성
            try:
                user_data = Student.objects.get(userID=userID)
                userName = user_data.username
                userType = "student"
            except Student.DoesNotExist:
                try:
                    user_data = Professor.objects.get(userID=userID)
                    userName = user_data.username
                    userType = "professor"
                except Professor.DoesNotExist:
                    return render(request, "login.html", {"error": "아이디가 존재하지 않습니다."})

            if check_password(password, user_data.password):
                request.session["userID"] = userID
                request.session["userName"] = userName
                request.session["userType"] = userType
                request.session["email"] = user_data.email
                return redirect("/toast_cal/")
            else:
                return render(request, "login.html", {"error": "비밀번호가 일치하지 않습니다."})
    else:
        return render(request, "login.html")


# 로그아웃
def logout(request):
    request.session.pop("userID")
    request.session.pop("userName")
    request.session.pop("userType")
    request.session.pop("email")

    return redirect("login")


# 아이디 / 비밀번호 찾는 페이지
def findInfo(request):
    return render(request, "findInfo.html")


# 아이디 찾기
def findId(request):
    if request.method == "POST":
        userType = request.POST["userType"]
        username = request.POST["username"]
        department = request.POST["department"]
        phone = request.POST["phone"]

        if userType == "student":
            try:
                user_data = Student.objects.get(
                    username=username, department=department, phone=phone
                )
                return render(
                    request,
                    "getMessage.html",
                    {"message": user_data.userID, "sep": "findId"},
                )
            except Student.DoesNotExist:
                return render(
                    request,
                    "getMessage.html",
                    {"message": "일치하는 아이디가 없습니다.", "log_sep": "false"},
                )
        elif userType == "professor":
            try:
                user_data = Professor.objects.get(
                    username=username, department=department, phone=phone
                )
                return render(
                    request,
                    "getMessage.html",
                    {"message": user_data.userID, "sep": "findId"},
                )
            except Professor.DoesNotExist:
                return render(
                    request,
                    "getMessage.html",
                    {"message": "일치하는 아이디가 없습니다.", "log_sep": "false"},
                )

    return render(request, "findId.html")


# 비밀번호 찾기
def findPass(request):
    if request.method == "POST":
        userType = request.POST["userType"]
        userID = request.POST["userID"]
        username = request.POST["username"]
        department = request.POST["department"]

        if userType == "student":
            try:
                user_data = Student.objects.get(
                    pk=userID, username=username, department=department
                )
                update = Student.objects.filter(
                    pk=userID, username=username, department=department
                ).update(
                    department=user_data.department,
                    studentID=user_data.studentID,
                    username=user_data.username,
                    email=user_data.email,
                    password=make_password(user_data.userID),
                    phone=user_data.phone,
                )
                return render(
                    request,
                    "getMessage.html",
                    {"message": "임시 비밀번호로 변경합니다.(비밀번호는 ID와 일치)", "log_sep": "false"},
                )
            except Student.DoesNotExist:
                return render(
                    request,
                    "getMessage.html",
                    {"message": "데이터가 일치하지 않습니다.", "log_sep": "false"},
                )
        elif userType == "professor":
            try:
                user_data = Professor.objects.get(
                    pk=userID, username=username, department=department
                )
                update = Professor.objects.filter(
                    pk=userID, username=username, department=department
                ).update(
                    department=user_data.department,
                    username=user_data.username,
                    email=user_data.email,
                    password=make_password(user_data.userID),
                    phone=user_data.phone,
                )
                return render(
                    request,
                    "getMessage.html",
                    {"message": "임시 비밀번호로 변경합니다.(비밀번호는 ID와 일치)", "log_sep": "false"},
                )
            except Professor.DoesNotExist:
                return render(
                    request,
                    "getMessage.html",
                    {"message": "데이터가 일치하지 않습니다.", "log_sep": "false"},
                )

    return render(request, "findPass.html")


# 비밀번호 변경
def changePw(request):
    if request.method == "POST":
        userType = request.POST["userType"]
        userID = request.POST["userID"]
        password = request.POST["password"]
        password2 = request.POST["password2"]
        password2_check = request.POST["password2_check"]

        if userType == "student":

            user_data = Student.objects.get(pk=userID)

            if check_password(password, user_data.password):
                if password2 == password2_check:
                    try:
                        update = Student.objects.filter(pk=userID).update(
                            department=user_data.department,
                            studentID=user_data.studentID,
                            username=user_data.username,
                            email=user_data.email,
                            password=make_password(password2),
                            phone=user_data.phone,
                        )
                        if request.session._session:
                            request.session.pop("userID")
                            request.session.pop("userName")
                            request.session.pop("userType")
                            request.session.pop("email")

                        return render(
                            request,
                            "getMessage.html",
                            {"message": "비밀번호가 변경되었습니다.", "sep": "changePw"},
                        )
                    except Student.DoesNotExist:
                        return render(
                            request,
                            "getMessage.html",
                            {"message": "잘못입력된 값이 있습니다.", "sep": "changePw"},
                        )
                else:
                    return render(
                        request,
                        "getMessage.html",
                        {"message": "새로입력한 비밀번호가 일치하지않습니다.", "sep": "changePw"},
                    )
            else:
                return render(
                    request,
                    "getMessage.html",
                    {"message": "비밀번호가 다릅니다.", "sep": "changePw"},
                )

        elif userType == "professor":

            user_data = Professor.objects.get(pk=userID)

            if check_password(password, user_data.password):
                if password2 == password2_check:
                    try:

toast_cal/templates/changePw.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'styles/signup.css' %}" rel="stylesheet">
    <title>비밀번호 변경</title>
</head>

<body>
    <div id="page">
        <div id="header" role="banner">
            <a href="" class="main_logo">
                비밀번호 변경
            </a>
        </div>
    </div>
    <form id="change_pw_form" method="POST" action="{% url 'changePw' %}">
        {% csrf_token %}
        <div id="container" role="main">
            <div id="content">
                <div>
                    <h3 class="join_title">
                        <label for="usersep">구분</label>
                    </h3>
                    <select id="select_area" name="userType">

                        {% if request.session.userID %}
                        {% if request.session.userType == "student" %}
                        <option value="student" selected>학생</option>
                        <option value="professor">교수</option>
                        {% elif request.session.userType == "professor" %}
                        <option value="student">학생</option>
                        <option value="professor" selected>교수</option>
                        {% endif %}
                        {% else %}
                        <option value="student">학생</option>
                        <option value="professor">교수</option>
                        {% endif %}
                    </select>
                </div>
                <div>
                    <h3 class="join_title">
                        <label for="userid">아이디</label>
                    </h3>
                    <span id="select_area">
                        {% if request.session.userID %}
                        <input type="text" name="userID" class="user_info" maxlength="20"
                            value="{{ request.session.userID }}">
                        {% else %}
                        <input type="text" name="userID" class="user_info" maxlength="20" placeholder="아이디">
                        {% endif %}
                    </span>
                </div>
                <div>
                    <h3 class="join_title">
                        <label for="psw1">비밀번호</label>
                    </h3>
                    <span class="ps_box">
                        <input type="password" name="password" class="user_info" maxlength="20" placeholder="비밀번호">
                    </span>
                </div>
                <div>
                    <h3 class="join_title">
                        <label for="psw2">새 비밀번호</label>
                    </h3>
                    <span class="ps_box">
                        <input type="password" name="password2" class="user_info" maxlength="20" placeholder="새 비밀번호">
                    </span>
                </div>
                <div>
                    <h3 class="join_title">
                        <label for="psw2">새 비밀번호 확인</label>
                    </h3>
                    <span class="ps_box">
                        <input type="password" name="password2_check" class="user_info" maxlength="20"
                            placeholder="새 비밀번호 확인">
                    </span>
                </div>
                <div class="btn_area">
                    <input type="submit" class="btn_type" name="submit" value="변경하기">
                </div>
            </div>
        </div>
    </form>
</body>

</html>

toast_cal/templates/findId.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <title>아이디 찾기</title>
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <link rel="stylesheet" href="{% static 'styles/signup.css' %}">
</head>

<body>

    <div id="page">
        <div id="header" role="banner">
            <p class="title">
                아이디 찾기
            </p>
        </div>
    </div>
    <form id="newUser_form" method="POST" action="{% url 'findId' %}">
        {% csrf_token %}
        <div id="container" role="main">
            <div id="content">
                <div>
                    <h3 class="join_title">
                        <label for="usersep">구분</label>
                    </h3>
                    <select id="select_area" name="userType">
                        <option value="student">학생</option>
                        <option value="professor">교수</option>
                    </select>
                </div>
                <div>
                    <h3 class="join_title">
                        <label for="username">이름</label>
                    </h3>
                    <span class="ps_box">
                        <input type="text" name="username" class="user_info" maxlength="20" placeholder="이름">
                    </span>
                </div>
                <div>
                    <h3 class="join_title">
                        <label for="userdep">학과</label>
                    </h3>
                    <span class="ps_box">
                        <input type="text" name="department" class="user_info" maxlength="20" placeholder="학과">
                    </span>
                </div>
                <div>
                    <h3 class="join_title">
                        <label for="phone">전화번호</label>
                    </h3>
                    <span class="ps_box">
                        <input type="text" name="phone" class="user_info" maxlength="100" placeholder="-제외하고 입력">
                    </span>
                </div>
                <div class="btn_area">
                    <input type="submit" class="btn_type" value="찾기">
                </div>
            </div>
        </div>
    </form>
</body>

</html>

toast_cal/templates/findInfo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>아이디/비밀번호 찾기</title>
    <link rel="stylesheet" href="{% static 'styles/findInfo.css' %}">
</head>

<body>
    <div class="main">
        <p>
            <a href="{% url 'index' %}">HS Calendar</a>
        </p>
    </div>
    <div id="content">
        <ul class="find_list">
            <li>
                <a href="{% url 'findId' %}" class="find">
                    아이디 찾기
                    <span>></span>
                </a>
            </li>
            <li>
                <a href="{% url 'findPass' %}" class="find">
                    비밀번호 찾기
                    <span>></span>
                </a>
            </li>
            <li>
                <a href="{% url 'changePw' %}" class="find">
                    비밀번호 변경
                    <span>></span>
                </a>
            </li>
        </ul>
    </div>
</body>

</html>

toast_cal/templates/findPass.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <title>비밀번호 찾기</title>
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <link rel="stylesheet" href="{% static 'styles/signup.css' %}">
</head>

<body>

    <div id="page">
        <div id="header" role="banner">
            <p class="title">
                비밀번호 찾기
            </p>
        </div>
    </div>
    <form id="newUser_form" method="POST" action="{% url 'findPass' %}">
        {% csrf_token %}
        <div id="container" role="main">
            <div id="content">
                <div>
                    <h3 class="join_title">
                        <label for="usersep">구분</label>
                    </h3>
                    <select id="select_area" name="userType">
                        <option value="student">학생</option>
                        <option value="professor">교수</option>
                    </select>
                </div>
                <div>
                    <h3 class="join_title">
                        <label for="userid">아이디</label>
                    </h3>
                    <span id="select_area">
                        <input type="text" name="userID" class="user_info" maxlength="20" placeholder="아이디">
                    </span>
                </div>
                <div>
                    <h3 class="join_title">
                        <label for="username">이름</label>
                    </h3>
                    <span class="ps_box">
                        <input type="text" name="username" class="user_info" maxlength="20" placeholder="이름">
                    </span>
                </div>
                <div>
                    <h3 class="join_title">
                        <label for="userdep">학과</label>
                    </h3>
                    <span class="ps_box">
                        <input type="text" name="department" class="user_info" maxlength="20" placeholder="학과">
                    </span>
                </div>
                <div class="btn_area">
                    <input type="submit" class="btn_type" value="찾기">
                </div>
            </div>
        </div>
    </form>
</body>

</html>

toast_cal/templates/getMessage.html
<script>
    if("{{ log_sep }}" == "true") {
        alert("{{ message }}");
        window.location.href = "{% url 'toast_cal:manageInfo' %}";
    }
    else if("{{ sep }}" == "changePw") {
        alert("{{ message }}");
        window.location.href = "{% url 'login' %}";
    }
    else if("{{ sep }}" == "signout") {
        alert("{{ message }}");
        window.location.href = "{% url 'index' %}";
    }
    else {
        alert("{{ message }}");
        window.location.href = "{% url 'findInfo' %}";
    }
</script>

toast_cal/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>main</title>
    <link rel="stylesheet" href="{% static 'styles/index.css' %}">
</head>

<body>
    <div class="main">
        <h1>HS Calendar</h1>
        <div id="content">학생과 교수사이의 시험, 공강 일정조율 프로그램</div>
        <div id="wrap-box">
            {% if request.session.userID %}
            <div class="box">
                <div class="box-content">
                    <a href=" {% url 'toast_cal:calendar' %}">
                        <p class="main-btn">캘린더</p>
                    </a>
                    <div class="detail"></div>
                </div>
            </div>
            {% else %}
            <div class="box">
                <div class="box-content">
                    <a href=" {% url 'login' %}" class="first">
                        <p class="main-btn">로그인</p>
                    </a>
                    <div class="detail"></div>
                </div>
            </div>
            <div class="box">
                <div class="box-content">
                    <a href=" {% url 'signup' %}">
                        <p class="main-btn">회원가입</p>
                    </a>
                    <div class="detail"></div>
                </div>
            </div>
            {% endif %}
        </div>


    </div>
</body>

</html>

toast_cal/templates/manageInfo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>내 정보 관리</title>
    <link rel="stylesheet" href="{% static 'styles/findInfo.css' %}">
</head>

<body>
    <div class="main">
        <p>
            <a href="{% url 'index' %}">HS Calendar</a>
        </p>
    </div>
    <div id="content">
        <ul class="find_list">
            <li>
                <a href="{% url 'toast_cal:loginInfo' %}" class="find">
                    개인정보 변경
                    <span>></span>
                </a>
            </li>
            <li>
                <a href="{% url 'changePw' %}" class="find">
                    비밀번호 변경
                    <span>></span>
                </a>
            </li>
            <li>
                <a href="{% url 'toast_cal:signout' %}" class="find">
                    회원 탈퇴
                    <span>></span>
                </a>
            </li>
        </ul>
    </div>
</body>

</html>

toast_cal/templates/modifyInfo.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <title>개인정보 변경</title>
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <link rel="stylesheet" href="{% static 'styles/signup.css' %}">
</head>

<body>

    <div id="page">
        <div id="header" role="banner">
            <a href="" class="main_logo">
                개인정보 변경
            </a>
        </div>
    </div>
    <form id="newUser_form" method="POST" action="{% url 'toast_cal:modifyInfo' %}">
        {% csrf_token %}
        <div id="container" role="main">
            <div id="content">
                <div>
                    <h3 class="join_title">
                        <label for="username">이름</label>
                    </h3>
                    <span class="ps_box">
                        <input type="text" name="username" class="user_info" maxlength="20" value="{{ username }}">
                    </span>
                </div>
                <div>
                    <h3 class="join_title">
                        <label for="userdep">학과</label>
                    </h3>
                    <span class="ps_box">
                        <input type="text" name="department" class="user_info" maxlength="20" value="{{ department }}">
                    </span>
                    <h3 class="join_title">
                        <label for="userno">학번</label>
                    </h3>
                    <span class="ps_box">
                        <input type="text" name="studentID" class="user_info" maxlength="20" placeholder="학번(학생만 입력)" value="{{ studentID }}">
                    </span>
                </div>

                <div>
                    <h3 class="join_title">
                        <label for="email">이메일</label>
                    </h3>
                    <span class="ps_box">
                        <input type="text" id="email" name="email" class="user_info" maxlength="100" value="{{ email }}">
                    </span>
                </div>
                <div>
                    <h3 class="join_title">
                        <label for="phone">전화번호</label>
                    </h3>
                    <span class="ps_box">
                        <input type="text" name="phone" class="user_info" maxlength="100" value="{{ phone }}">
                    </span>
                </div>
                <div class="btn_area">
                    <input type="submit" class="btn_type" value="변경하기">
                </div>
            </div>
        </div>
    </form>
</body>

</html>

toast_cal/templates/signout.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <title>회원탈퇴</title>
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <link rel="stylesheet" href="{% static 'styles/signup.css' %}">
</head>

<body>

    <div id="page">
        <div id="header" role="banner">
            <a href="" class="main_logo">
                회원탈퇴
            </a>
        </div>
    </div>
    <form id="newUser_form" method="POST" action="{% url 'toast_cal:signout' %}">
        {% csrf_token %}
        <div id="container" role="main">
            <div id="content">
                <div class="caution_area">
                    <h2>주의</h2>
                    <span class="caution">회원탈퇴를 진행하면 개인 일정 및 강의 시간표가 삭제되며,
                        이 과정의 진행으로 인해 소멸된 개인 일정데이터는 복구할 수 없습니다.</span>
                </div>
                <div>
                    <h3 class="join_title">
                        <label>따라서 입력해 주세요.</label>
                    </h3>
                    <span class="ps_box">
                        <input type="text" name="confirm" class="user_info" maxlength="20" placeholder="탈퇴합니다">
                    </span>
                </div>
                <div class="btn_area">
                    <input type="submit" class="btn_type" value="탈퇴하기">
                </div>
            </div>
        </div>
    </form>
</body>

</html>